// newsletter renders a markdown file into a paste-ready branded newsletter
// HTML file for hand-sending from Gmail.
//
// Pipeline: goldmark (markdown → HTML) → CTA-button rewrite → wrap in the
// branded layout (layout.html, embedded) → premailer (push the layout's
// <style> rules onto every element inline, because Gmail strips <style>
// blocks on paste).
//
// The source can be a Hugo news post — YAML (---) or TOML (+++) front matter
// is stripped, and its title: becomes the document title unless -title is
// given. This makes frontend/content/news/ the single source: publish the
// post on the site, then render the same file for the member mail.
//
// Usage from the api/ directory:
//
//	go run ./cmd/newsletter -in ../frontend/content/news/august-2026-update.md \
//	    -out ../marketing-materials/email-templates/2026-08-newsletter.html
//
// Markdown conventions:
//   - ## headings become branded section headings.
//   - A paragraph containing ONLY a link becomes an orange CTA button:
//     [RSVP — MakerMeet](https://calendar.google.com/...)
//   - End a line with a backslash for a <br> (e.g. before a sign-off name).
//
// The output lands next to the source as <name>.html unless -out is given.
// Open it in a browser, select all, copy, paste into a Gmail compose window.
package main

import (
	"bytes"
	_ "embed"
	"flag"
	"fmt"
	"html/template"
	"log"
	"os"
	"regexp"
	"strings"

	"github.com/vanng822/go-premailer/premailer"
	"github.com/yuin/goldmark"
	"github.com/yuin/goldmark/extension"
)

//go:embed layout.html
var layoutHTML string

// A paragraph whose entire content is one link is promoted to a CTA button.
var buttonRe = regexp.MustCompile(`<p><a href="([^"]*)"[^>]*>(.+?)</a></p>`)

const buttonHTML = `<table role="presentation" cellpadding="0" cellspacing="0" border="0" style="border-collapse: collapse; margin: 24px 0;"><tr>` +
	`<td align="center" bgcolor="#F68048" style="border-radius: 10px;">` +
	`<a href="$1" style="display: inline-block; padding: 12px 28px; font-family: 'Roboto', sans-serif; font-size: 16px; font-weight: 600; line-height: 20px; color: #ffffff; text-decoration: none; background-color: #F68048; border-radius: 10px;">$2</a>` +
	`</td></tr></table>`

func main() {
	in := flag.String("in", "", "markdown source file — plain markdown or a Hugo post with front matter (required)")
	out := flag.String("out", "", "output HTML file (default: source path with .html extension)")
	title := flag.String("title", "", "document <title>; browser-tab only, not visible in the email (default: front matter title, else a generic one)")
	flag.Parse()

	if *in == "" {
		flag.Usage()
		log.Fatal("-in is required")
	}
	src, err := os.ReadFile(*in)
	if err != nil {
		log.Fatalf("read %s: %v", *in, err)
	}

	body, fmTitle := stripFrontMatter(src)
	docTitle := pick(*title, fmTitle, "O'Town Makerspace — newsletter")

	md := goldmark.New(goldmark.WithExtensions(extension.GFM, extension.Typographer))
	var rendered bytes.Buffer
	if err := md.Convert(body, &rendered); err != nil {
		log.Fatalf("render markdown: %v", err)
	}
	content := buttonRe.ReplaceAllString(rendered.String(), buttonHTML)

	tmpl := template.Must(template.New("layout").Parse(layoutHTML))
	var page bytes.Buffer
	page.WriteString(fmt.Sprintf("<!-- Generated by api/cmd/newsletter from %s — edit the .md and re-run instead of hand-editing. -->\n", *in))
	err = tmpl.Execute(&page, struct {
		Title   string
		Content template.HTML
	}{docTitle, template.HTML(content)})
	if err != nil {
		log.Fatalf("execute layout: %v", err)
	}

	opts := premailer.NewOptions()
	opts.RemoveClasses = true
	prem, err := premailer.NewPremailerFromString(page.String(), opts)
	if err != nil {
		log.Fatalf("premailer parse: %v", err)
	}
	inlined, err := prem.Transform()
	if err != nil {
		log.Fatalf("premailer transform: %v", err)
	}

	target := *out
	if target == "" {
		target = strings.TrimSuffix(*in, ".md") + ".html"
	}
	if err := os.WriteFile(target, []byte(inlined), 0o644); err != nil {
		log.Fatalf("write %s: %v", target, err)
	}
	log.Printf("✓ %s → %s", *in, target)
}

var fmTitleRe = regexp.MustCompile(`(?m)^title\s*[:=]\s*"?([^"\n]+?)"?\s*$`)

// stripFrontMatter removes a leading YAML (---) or TOML (+++) front matter
// block, if present, and returns the markdown body plus the title declared in
// the block ("" when absent). Anything fancier than a top-level title line
// (nested keys, folded scalars) is out of scope for a build tool this small.
func stripFrontMatter(src []byte) (body []byte, title string) {
	s := string(src)
	var delim string
	switch {
	case strings.HasPrefix(s, "---\n"), strings.HasPrefix(s, "---\r\n"):
		delim = "---"
	case strings.HasPrefix(s, "+++\n"), strings.HasPrefix(s, "+++\r\n"):
		delim = "+++"
	default:
		return src, ""
	}
	rest := s[strings.IndexByte(s, '\n')+1:]
	end := strings.Index(rest, "\n"+delim)
	if end < 0 {
		return src, ""
	}
	block := rest[:end]
	after := rest[end+1+len(delim):]
	if i := strings.IndexByte(after, '\n'); i >= 0 {
		after = after[i+1:]
	} else {
		after = ""
	}
	if m := fmTitleRe.FindStringSubmatch(block); m != nil {
		title = strings.TrimSpace(m[1])
	}
	return []byte(after), title
}

func pick(opts ...string) string {
	for _, s := range opts {
		if s != "" {
			return s
		}
	}
	return ""
}
