// marketing-materials/google-ads/_layout.typ
// Google Display banners — shared helpers. Each banner sets its own page
// size since the IAB Display formats vary (300×250, 728×90, etc.).
// Ported from esio-website/marketing-typst/google-ads/_layout.typ; the logo
// is the rasterized PNG (export-logos.sh) and footer text is otm's.

#import "../tokens.typ": *

#let setup-page(width, height) = {
  body => {
    set page(width: width, height: height, margin: 0pt, fill: surface)
    set text(font: primary-font, fill: on-surface)
    set par(leading: 0.5em)
    body
  }
}

// Rasterized brand lockup (generated by ../export-logos.sh).
#let logo-src = if theme == "light" {
  "/marketing-materials/assets/logos/logo-light.png"
} else {
  "/marketing-materials/assets/logos/logo-dark.png"
}

#let muted = on-surface.transparentize(35%)

// Small CTA pill — parameterised because banners vary widely.
#let cta-pill(label, size: 14pt, pad-x: 14pt, pad-y: 8pt) = box(
  fill: primary, inset: (x: pad-x, y: pad-y), radius: 999pt,
)[
  #text(font: primary-font, size: size, weight: 700, fill: on-primary)[#label →]
]

// Small decorative orb — primary-tinted circle. Returns a place(...) call.
#let orb(pos, radius, dx: 0pt, dy: 0pt, opacity: 18%) = place(
  pos, dx: dx, dy: dy,
  circle(radius: radius, fill: primary.transparentize(100% - opacity)),
)
