// marketing-materials/poster/_layout.typ
// A4 print poster (210mm × 297mm) — page setup + contact-channel color coding.
//
// Follows the same skeleton as square/_layout.typ (orb decoration, rasterized
// logo PNGs from export-logos.sh, Material Symbols icons), but sized in mm
// because this format targets paper, not pixel-spec ad slots. The SVG is the
// print master; render.sh rasterizes the PNG at 300ppi for print quality.

#import "../tokens.typ": *
// QR generation (zint compiled to wasm). Downloaded from the Typst package
// registry on first compile, then cached in ~/.cache/typst — later renders
// are offline.
#import "@preview/tiaoma:0.3.0": qrcode

#let poster-setup(body) = {
  set page(width: 210mm, height: 297mm, margin: 0mm, fill: surface)
  set text(font: primary-font, fill: on-surface, size: 12pt,
    top-edge: "ascender", bottom-edge: "descender")
  set par(leading: 0.3em)

  // Decorative orbs — same chrome as the social templates.
  place(top + right, dx: 42mm, dy: -48mm,
    circle(radius: 62mm, fill: primary.transparentize(85%)))
  place(bottom + left, dx: -34mm, dy: 30mm,
    circle(radius: 55mm, fill: surface-container-high.transparentize(45%)))

  body
}

// Rasterized brand marks — generated by ../export-logos.sh (gitignored).
#let logo-src = if theme == "light" {
  "/marketing-materials/assets/logos/logo-light.png"
} else {
  "/marketing-materials/assets/logos/logo-dark.png"
}
#let gear-src = if theme == "light" {
  "/marketing-materials/assets/logos/individual/gear-mark-transparent.png"
} else {
  "/marketing-materials/assets/logos/individual/gear-mark-white-transparent.png"
}

#let muted = on-surface.transparentize(35%)

// ── Contact-channel color coding ─────────────────────────────────────────────
// One hue per channel so the poster scans at a glance. All four are
// brand-sanctioned: they are the site's CSS palette (frontend/input.css) —
// accent #F68048, secondary-2 #1A2CA3, accent-2 #E75008, secondary #0D1A63.
// Dark theme lightens the two hues that would sink into the navy card fill.
#let channel = if theme == "light" {
  (
    email:    rgb("#F68048"), // accent orange
    location: rgb("#1A2CA3"), // secondary-2 blue
    hours:    rgb("#E75008"), // accent-2 deep orange
  )
} else {
  (
    email:    rgb("#F68048"),
    location: rgb("#93A5F1"), // secondary-2, lightened for navy surfaces
    hours:    rgb("#FF9B66"), // accent-2, lightened for navy surfaces
  )
}

// Social chips keep the platforms' own brand colors — that IS their color
// code, and it reads identically on light and dark paper.
#let social = (
  facebook:  rgb("#1877F2"),
  instagram: rgb("#E4405F"),
  discord:   rgb("#5865F2"),
)

#let icon(name, size, color) = text(
  font: "Material Symbols Outlined", size: size, fill: color,
  features: ("liga": 1),
)[#name]

// Color-coded contact card: tinted icon chip + colored small-caps label,
// value in on-surface. Mirrors the site's contact page cards (contact.html:
// accent-tinted icon circle over a surface card).
#let contact-card(color, icon-name, label, value, note: none) = block(
  fill: card-bg, stroke: 1pt + card-border, radius: 5mm, width: 100%,
  inset: (x: 9mm, y: 5.5mm),
)[
  #grid(
    columns: (auto, 1fr), column-gutter: 8mm, align: horizon + left,
    box(width: 14mm, height: 14mm, fill: color.transparentize(85%), radius: 999pt,
      align(center + horizon, icon(icon-name, 23pt, color))),
    [
      #text(font: display-font, size: 11pt, weight: 700, tracking: 1.8pt, fill: color)[#upper(label)]
      #v(6pt, weak: true)
      #text(font: primary-font, size: 17pt, weight: 700, fill: on-surface)[#value]
      #if note != none [
        #v(5pt, weak: true)
        #text(font: primary-font, size: 10.5pt, weight: 500, fill: muted)[#note]
      ]
    ],
  )
]

// QR tile: navy QR on a white card (always white, even in dark theme — QR
// modules need a light, uniform background to scan), with a platform-colored
// pill underneath carrying the color code + icon + name.
#let qr-tile(color, icon-name, label, url) = block(
  fill: white, stroke: 1pt + card-border, radius: 4mm,
  inset: (x: 3.5mm, top: 3.5mm, bottom: 3mm),
)[
  #align(center)[
    #qrcode(url, width: 22mm, options: (fg-color: rgb("#0D1A63"), bg-color: white))
    #v(2.5mm, weak: true)
    #box(fill: color, radius: 999pt, inset: (x: 4mm, y: 2.2mm))[
      #grid(
        columns: (auto, auto), column-gutter: 2mm, align: horizon,
        icon(icon-name, 11pt, white),
        text(font: primary-font, size: 10pt, weight: 700, fill: white)[#label],
      )
    ]
  ]
]

// Full-bleed footer band — the website's color code is the brand band itself
// (navy in light theme, orange in dark; tokens flip secondary/on-secondary).
// The domain stays as text (posters need a human-readable address) with its
// QR alongside; scan-hint under the QR.
#let footer-band(site, site-url, tagline, hint) = block(
  width: 100%, fill: secondary, inset: (x: 16mm, y: 5.5mm),
)[
  #grid(
    columns: (1fr, auto), align: (left + horizon, right + horizon),
    [
      #text(font: display-font, size: 12pt, weight: 500, tracking: 3pt,
        fill: on-secondary.transparentize(30%))[#tagline]
      #v(8pt, weak: true)
      #text(font: display-font, size: 26pt, weight: 700, fill: on-secondary)[#site]
    ],
    align(center)[
      #box(fill: white, radius: 2mm, inset: 2mm)[
        #qrcode(site-url, width: 15mm, options: (fg-color: rgb("#0D1A63"), bg-color: white))
      ]
      #v(1.5mm, weak: true)
      #text(font: primary-font, size: 8pt, weight: 500,
        fill: on-secondary.transparentize(25%))[#hint]
    ],
  )
]
