// marketing-materials/square/_layout.typ
// Universal social slide — 1080×1080 square page setup + shared chrome.
//
// One square asset satisfies every social feed (Facebook, Instagram,
// LinkedIn). Ported from esio-website/marketing-typst/square/_layout.typ,
// re-skinned for O'Town Makerspace:
//   - the brand logo is a *rasterized* PNG (export-logos.sh flattens the
//     composite lockup SVGs, which Typst can't load directly),
//   - footer reads otownmakerspace.dk,
//   - decoration is brand-color orbs (otm ships no character illustrations).

#import "../tokens.typ": *

// Size scale for the 1080×1080 canvas. If a slide overflows, Typst spills
// onto a 2nd page and render.sh's SVG export errors — that's the fit check.
#let SIZES = (
  h-xxl: 84pt,  h-xl: 70pt,  h-l: 60pt,  h-m: 44pt,  h-s: 30pt,
  eyebrow: 17pt, lede: 21pt, pageno: 18pt,
  logo: 96pt,
  pad-x: 72pt, pad-top: 64pt, pad-bottom: 72pt,
)

#let slide-setup(body) = {
  set page(width: 1080pt, height: 1080pt, margin: 0pt, fill: surface)
  set text(font: primary-font, fill: on-surface, size: 16pt,
    top-edge: "ascender", bottom-edge: "descender")
  set par(leading: 0.3em)

  // Decorative orbs — top-right primary tint + bottom-left elevation.
  place(top + right, dx: 160pt, dy: -180pt,
    circle(radius: 240pt, fill: primary.transparentize(82%)))
  place(bottom + left, dx: -120pt, dy: 200pt,
    circle(radius: 210pt, fill: surface-container-high.transparentize(45%)))

  body
}

// Rasterized brand lockup — generated by ../export-logos.sh. Run that script
// before render.sh; the PNGs are gitignored (regenerate, don't commit).
#let logo-src = if theme == "light" {
  "/marketing-materials/assets/logos/logo-light.png"
} else {
  "/marketing-materials/assets/logos/logo-dark.png"
}

#let muted = on-surface.transparentize(35%)

#let header(page-no, total: "05") = grid(
  columns: (1fr, auto),
  align: horizon,
  image(logo-src, height: SIZES.logo),
  text(font: primary-font, size: SIZES.pageno, weight: 700, tracking: 3pt, fill: muted)[
    #page-no / #total
  ],
)

#let footer() = text(font: primary-font, size: 18pt, weight: 700, fill: muted)[otownmakerspace.dk]

// Extra brand blob — focal accent in the lower-right of a slide.
#let bg-decoration() = place(
  bottom + right, dx: 120pt, dy: 150pt,
  circle(radius: 300pt, fill: primary.transparentize(80%)),
)

// Horizontal card (icon left, title+body right).
#let h-card(icon, title, body-text) = block(
  fill: card-bg, stroke: 1pt + card-border, radius: 18pt,
  inset: (x: 26pt, y: 20pt), width: 100%,
)[
  #grid(
    columns: (auto, 1fr), column-gutter: 22pt, align: horizon + left,
    text(font: "Material Symbols Outlined", size: 46pt, fill: primary, features: ("liga": 1))[#icon],
    [
      #text(font: primary-font, size: 22pt, weight: 700, fill: on-surface)[#title]
      #v(4pt, weak: true)
      #text(font: primary-font, size: 13pt, weight: 500, fill: muted)[#body-text]
    ],
  )
]

// Feature panel with a Material Symbols icon (icon-name is a ligature).
#let feature(icon-name, title, body-text) = block(
  fill: card-bg, stroke: 1pt + card-border, radius: 14pt,
  inset: 18pt, width: 100%,
)[
  #text(font: "Material Symbols Outlined", size: 40pt, fill: primary, features: ("liga": 1))[#icon-name]
  #v(8pt, weak: true)
  #text(font: primary-font, size: 20pt, weight: 700, fill: on-surface)[#title]
  #v(4pt, weak: true)
  #text(font: primary-font, size: 12pt, weight: 500, fill: muted)[#body-text]
]

#let cta-pill(label) = box(
  fill: primary, inset: (x: 40pt, y: 20pt), radius: 999pt,
)[
  #text(font: primary-font, size: 32pt, weight: 700, fill: on-primary)[#label]
]

// Material Symbols `arrow_right_alt` — focal arrow on 01-hook.
#let big-arrow() = text(font: "Material Symbols Outlined", size: 150pt, fill: primary, features: ("liga": 1))[arrow_right_alt]

#let foot-arrow() = text(font: "Material Symbols Outlined", size: 64pt, fill: primary, features: ("liga": 1))[arrow_right_alt]

#let footer-with-arrow() = grid(
  columns: (1fr, auto, 1fr),
  align: (left + bottom, center + bottom, right + bottom),
  text(font: primary-font, size: 18pt, weight: 700, fill: muted)[otownmakerspace.dk],
  foot-arrow(),
  [],
)
